### ISSUE TITLE
User Login / Logout

### ISSUE THREAD

**Issue by jessicakarpovich** [jessicakarpovich/capstone#11]
Configure oAuth with Firebase. Test login and logout.

**Comment by brandonbrown** [comment]
Are you limiting this to email login types or using the social log-in capabilities offered through firebase?

**Comment by jessicakarpovich** [comment]
I'm going to use the social log-in offered through firebase. 

Logging in will be completely optional and if the user chooses to skip logging in, they won't be shown the log in screen when opening the app. If they later choose to log in, they will be able to do so by going to Settings.

**Comment by jessicakarpovich** [comment]
#24 Added user login and logout. Tested with user data based on user uid.
