### ISSUE TITLE
Populate DB Content

### ISSUE THREAD

**Issue by jessicakarpovich** [jessicakarpovich/capstone#12]
Enter main content into database that will be accessed by the users.
* Hiragana
* Katakana
* Kanji
* Phrases

**Comment by brandonbrown** [comment]
These are all living on firebase? Look into their Firestore products for these type of items, rather than the real-time database (the firebase standard)

**Comment by jessicakarpovich** [comment]
Thank you for the suggestion! This data will be stored using Cloud Firestore.

**Comment by jessicakarpovich** [comment]
Added content to Firestore db. Here is the content in a text file.
[dbContent.txt](https://github.com/jessicakarpovich/capstone/files/2453610/dbContent.txt)
