### ISSUE TITLE
Add Instructors as Collaborators

### ISSUE THREAD

**Issue by brandonbrown** [jessicakarpovich/capstone#2]
Please add the following github user accounts as collaborators on this project:

brandonbrown
markmichon
reactivepixel
emedialabs
thisisbrad
jerrytk214
jcavagna

**Comment by jessicakarpovich** [comment]
I added the users as collaborators.

**Comment by brandonbrown** [comment]
Other students reported eMediaLabs as not a user. Please add @eMediaLab to this repo

**Comment by jessicakarpovich** [comment]
I previously noticed eMediaLabs is not a user but eMediaLab is, so I added eMediaLab instead.
